apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 10
  labels:
    app: aos-api-envs
  name: aos-api-envs
spec:
  replicas: 1
  selector:
    app: aos-api-envs
    deploymentconfig: aos-api-envs
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: aos-api-envs
        deploymentconfig: aos-api-envs
    spec:
      containers:
      - env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: 172.30.93.229:5000/aos-api-envs/aos-api-envs@sha256:3a67298c0edfe8993fc7738c61b106e5973432731f0b3790ebac9174684218f5
        imagePullPolicy: Always
        name: aos-api-envs
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - aos-api-envs
      from:
        kind: ImageStreamTag
        name: aos-api-envs:latest
        namespace: aos-api-envs
    type: ImageChange
status:
  availableReplicas: 1
  observedGeneration: 10
  replicas: 1
  updatedReplicas: 1
